# Generated by Django 4.1.2 on 2022-10-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZANGEapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zangemodel',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='zangemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
