# Generated by Django 4.1.2 on 2022-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZANGEapp', '0002_zangemodel_url_alter_zangemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zangemodel',
            name='text',
            field=models.TextField(verbose_name='コンテンツ'),
        ),
    ]
