# Generated by Django 4.1.2 on 2022-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZANGEapp', '0003_alter_zangemodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='zangemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
