# Generated by Django 4.1.2 on 2022-11-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZANGEapp', '0004_zangemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='zangemodel',
            name='image',
        ),
    ]
